export const SET_FETCHING = 'SET_FETCHING';
export const UNSET_FETCHING = 'UNSET_FETCHING';

export const RECEIVE_AUTH = 'RECEIVE_AUTH';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_OUT = 'SIGN_OUT ';

export const AUTH_SIGN_IN_ERROR = 'AUTH_SIGN_IN_ERROR';
export const RECEIVE_USER_PROFILE = 'RECEIVE_USER_PROFILE';

export const RECEIVE_ALL_RECIPE = 'RECEIVE_ALL_RECIPE';
export const RECEIVE_SINGLE_RECIPE = 'RECEIVE_SINGLE_RECIPE';
export const RECEIVE_TOP_RECIPES = 'RECEIVE_TOP_RECIPES';

export const EDIT_RECIPE = 'EDIT_RECIPE';
export const EDIT_RECIPE_ERROR = 'EDIT_RECIPE_ERROR';

export const RECEIVE_USER_RECIPES = 'RECEIVE_USER_RECIPES';

export const ADD_RECIPE = "ADD_RECIPE";
export const ADD_RECIPE_ERROR = "ADD_RECIPE_ERROR";

