export const SET_FETCHING = 'SET_FETCHING';
export const UNSET_FETCHING = 'UNSET_FETCHING';

export const RECEIVE_AUTH = 'RECEIVE_AUTH';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_OUT = 'SIGN_OUT ';

export const AUTH_SIGN_IN_ERROR = 'AUTH_SIGN_IN_ERROR';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';

export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_SINGLE_RECIPE = 'GET_SINGLE_RECIPE';
export const GET_TOP_RECIPES = 'GET_TOP_RECIPES';

export const EDIT_RECIPE = 'EDIT_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';

export const GET_USER_RECIPES = 'GET_USER_RECIPES';
export const GET_USER_RECIPES_ERROR = 'GET_USER_RECIPES_ERROR';

export const GET_USER_FAVOURITE = 'GET_USER_FAVOURITE';
export const GET_USER_FAVOURITE_ERROR = 'GET_USER_FAVOURITE_ERROR';

export const ADD_RECIPE = 'ADD_RECIPE';
export const ADD_RECIPE_ERROR = 'ADD_RECIPE_ERROR';

export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const ADD_FAVOURITE_ERROR = 'ADD_FAVOURITE_ERROR';

export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_ERROR = 'ADD_REVIEW_ERROR';

export const SHOW_PAGINATION = 'SHOW_PAGINATION';

